//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientPlayingSOA.ServiceReferenceDepositos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="https://www.uca.edu.ni/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int MetaField;
        
        private int TotalField;
        
        private int UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Meta {
            get {
                return this.MetaField;
            }
            set {
                if ((this.MetaField.Equals(value) != true)) {
                    this.MetaField = value;
                    this.RaisePropertyChanged("Meta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.uca.edu.ni/", ConfigurationName="ServiceReferenceDepositos.wsRegistroDepositosSoap")]
    public interface wsRegistroDepositosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/AgregarDeposito", ReplyAction="*")]
        int AgregarDeposito(int cantidad, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/AgregarDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AgregarDepositoAsync(int cantidad, int idUsuario);
        
        // CODEGEN: Generating message contract since element name nombre from namespace https://www.uca.edu.ni/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/AgregarUsuario", ReplyAction="*")]
        clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse AgregarUsuario(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/AgregarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse> AgregarUsuarioAsync(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name ListaUsuariosResult from namespace https://www.uca.edu.ni/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/ListaUsuarios", ReplyAction="*")]
        clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse ListaUsuarios(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.uca.edu.ni/ListaUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse> ListaUsuariosAsync(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuario", Namespace="https://www.uca.edu.ni/", Order=0)]
        public clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequestBody Body;
        
        public AgregarUsuarioRequest() {
        }
        
        public AgregarUsuarioRequest(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.uca.edu.ni/")]
    public partial class AgregarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int meta;
        
        public AgregarUsuarioRequestBody() {
        }
        
        public AgregarUsuarioRequestBody(string nombre, int meta) {
            this.nombre = nombre;
            this.meta = meta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarUsuarioResponse", Namespace="https://www.uca.edu.ni/", Order=0)]
        public clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponseBody Body;
        
        public AgregarUsuarioResponse() {
        }
        
        public AgregarUsuarioResponse(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.uca.edu.ni/")]
    public partial class AgregarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AgregarUsuarioResult;
        
        public AgregarUsuarioResponseBody() {
        }
        
        public AgregarUsuarioResponseBody(int AgregarUsuarioResult) {
            this.AgregarUsuarioResult = AgregarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarios", Namespace="https://www.uca.edu.ni/", Order=0)]
        public clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequestBody Body;
        
        public ListaUsuariosRequest() {
        }
        
        public ListaUsuariosRequest(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaUsuariosRequestBody {
        
        public ListaUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuariosResponse", Namespace="https://www.uca.edu.ni/", Order=0)]
        public clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponseBody Body;
        
        public ListaUsuariosResponse() {
        }
        
        public ListaUsuariosResponse(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.uca.edu.ni/")]
    public partial class ListaUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public clientPlayingSOA.ServiceReferenceDepositos.Usuario[] ListaUsuariosResult;
        
        public ListaUsuariosResponseBody() {
        }
        
        public ListaUsuariosResponseBody(clientPlayingSOA.ServiceReferenceDepositos.Usuario[] ListaUsuariosResult) {
            this.ListaUsuariosResult = ListaUsuariosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsRegistroDepositosSoapChannel : clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsRegistroDepositosSoapClient : System.ServiceModel.ClientBase<clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap>, clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap {
        
        public wsRegistroDepositosSoapClient() {
        }
        
        public wsRegistroDepositosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsRegistroDepositosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRegistroDepositosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRegistroDepositosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AgregarDeposito(int cantidad, int idUsuario) {
            return base.Channel.AgregarDeposito(cantidad, idUsuario);
        }
        
        public System.Threading.Tasks.Task<int> AgregarDepositoAsync(int cantidad, int idUsuario) {
            return base.Channel.AgregarDepositoAsync(cantidad, idUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap.AgregarUsuario(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuario(request);
        }
        
        public int AgregarUsuario(string nombre, int meta) {
            clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest inValue = new clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest();
            inValue.Body = new clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.meta = meta;
            clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse retVal = ((clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap)(this)).AgregarUsuario(inValue);
            return retVal.Body.AgregarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse> clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap.AgregarUsuarioAsync(clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest request) {
            return base.Channel.AgregarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioResponse> AgregarUsuarioAsync(string nombre, int meta) {
            clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest inValue = new clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequest();
            inValue.Body = new clientPlayingSOA.ServiceReferenceDepositos.AgregarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.meta = meta;
            return ((clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap)(this)).AgregarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap.ListaUsuarios(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest request) {
            return base.Channel.ListaUsuarios(request);
        }
        
        public clientPlayingSOA.ServiceReferenceDepositos.Usuario[] ListaUsuarios() {
            clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest inValue = new clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest();
            inValue.Body = new clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequestBody();
            clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse retVal = ((clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap)(this)).ListaUsuarios(inValue);
            return retVal.Body.ListaUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse> clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap.ListaUsuariosAsync(clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest request) {
            return base.Channel.ListaUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosResponse> ListaUsuariosAsync() {
            clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest inValue = new clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequest();
            inValue.Body = new clientPlayingSOA.ServiceReferenceDepositos.ListaUsuariosRequestBody();
            return ((clientPlayingSOA.ServiceReferenceDepositos.wsRegistroDepositosSoap)(this)).ListaUsuariosAsync(inValue);
        }
    }
}
